# Modeling Cookie2 Data

## Importing all we need

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression , LinearRegression
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier , DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score, confusion_matrix,plot_confusion_matrix,cohen_kappa_score,accuracy_score,recall_score,precision_score,f1_score,classification_report

In [2]:
cookies2 = pd.read_csv("/Users/timeisenmenger/Desktop/Ironhack /Week8/ML-Competition/Modified-DataFrames/Cookies2.csv")
cookies2_new_test = pd.read_csv("/Users/timeisenmenger/Desktop/Ironhack /Week8/ML-Competition/Modified-DataFrames/Cookies2_new_test.csv")

In [3]:
cookies2.head()

sugar to flour ratio  sugar index  bake temp  chill time  calories  \
0                  0.25          9.5        300        15.0     136.0   
1                  0.23          3.3        520        34.0     113.0   
2                  0.18          1.9        360        33.0     106.0   
3                  0.18         10.5        490        41.0     124.0   
4                  0.24          2.4        770         6.0      33.0   

   grams baking soda  bake time  quality  weight  chocolate  oats  \
0               0.44       12.1        8    15.2          0     0   
1               0.48        8.4        7    12.4          0     0   
2               0.83       14.0        9     9.4          1     0   
3               0.35       10.5        7    12.2          1     0   
4               0.57        9.4        5    19.8          1     1   

   peanut butter  raisins  nuts  cubed  melted  
0              0        1     0      0       1  
1              0        1     0      0       1  
2              0        0     1      0       1  
3              0        0     0      0       1  
4              0        0     1      1       0

## Base for Modeling

In [4]:
# Setup X_train, X_test, y_train, y_test
X_train = cookies2.drop(columns = 'quality')
X_test = cookies2_new_test.drop(columns = 'quality')
y_train = cookies2["quality"]
y_test = cookies2_new_test["quality"]

In [5]:
# ScalerModel
scaler = StandardScaler()

In [6]:
scaler.fit(X_train)

StandardScaler()

In [7]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

## Linear Regression Model

In [31]:
grid = GridSearchCV(estimator = LinearRegression(), param_grid = {'fit_intercept':[True,False], 'normalize':[True,False], 'copy_X':[True, False]}, cv=10)
grid.fit(X_train_scaled, y_train)

GridSearchCV(cv=10, estimator=LinearRegression(),
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False],
                         'normalize': [True, False]})

In [32]:
grid.best_params_

{'copy_X': True, 'fit_intercept': True, 'normalize': True}

In [33]:
y_pred_test = grid.predict(X_test_scaled)
y_pred_test

array([8.34687782, 7.53832746, 7.75803358, 7.97360611, 7.59390535,
       7.00309757, 7.74682188, 7.88469895, 8.05734652, 7.5919487 ,
       7.69058066, 7.20340095, 7.28841608, 7.88617602, 8.13451902,
       7.39673864, 7.95314392, 6.89092483, 8.52036127, 8.19422646,
       7.83943058, 8.00681257, 8.26790083, 8.07456427, 7.7252051 ,
       7.83066013, 6.75764364, 7.7868077 , 7.82914841, 7.53287928,
       7.9650708 , 8.2867042 , 7.36423039, 7.29759935, 7.56155633,
       8.1887367 , 8.13898324, 7.98770465, 6.84797098, 7.74630431,
       8.27054976, 7.80729443, 7.78355576, 6.92257592, 7.32007341,
       7.18022176, 7.44505467, 8.18471055, 7.8535629 , 7.37789733,
       6.95945205, 7.86500097, 7.60684036, 7.42725649, 6.89052767,
       8.19666543, 7.66769062, 7.06774613, 7.7136177 , 8.90246961,
       7.49252073, 7.77130691, 7.09802943, 7.40055966, 8.30821973,
       7.53982607, 7.7348363 , 7.62250318, 7.24766237, 8.45132635,
       8.20463786, 8.47328543, 7.36587054, 6.59606237, 8.06963

In [40]:
prediction_array_dt_cookies = y_pred_test

In [42]:
prediction_array_dt_cookies

array([8.34687782, 7.53832746, 7.75803358, 7.97360611, 7.59390535,
       7.00309757, 7.74682188, 7.88469895, 8.05734652, 7.5919487 ,
       7.69058066, 7.20340095, 7.28841608, 7.88617602, 8.13451902,
       7.39673864, 7.95314392, 6.89092483, 8.52036127, 8.19422646,
       7.83943058, 8.00681257, 8.26790083, 8.07456427, 7.7252051 ,
       7.83066013, 6.75764364, 7.7868077 , 7.82914841, 7.53287928,
       7.9650708 , 8.2867042 , 7.36423039, 7.29759935, 7.56155633,
       8.1887367 , 8.13898324, 7.98770465, 6.84797098, 7.74630431,
       8.27054976, 7.80729443, 7.78355576, 6.92257592, 7.32007341,
       7.18022176, 7.44505467, 8.18471055, 7.8535629 , 7.37789733,
       6.95945205, 7.86500097, 7.60684036, 7.42725649, 6.89052767,
       8.19666543, 7.66769062, 7.06774613, 7.7136177 , 8.90246961,
       7.49252073, 7.77130691, 7.09802943, 7.40055966, 8.30821973,
       7.53982607, 7.7348363 , 7.62250318, 7.24766237, 8.45132635,
       8.20463786, 8.47328543, 7.36587054, 6.59606237, 8.06963

In [44]:
np.savetxt('/Users/timeisenmenger/Desktop/Ironhack /Week8/ML-Competition/Code/LR_cookies.csv', prediction_array_dt_cookies, delimiter=',')

## DecisionTree Model

In [34]:
grid_dt = GridSearchCV(estimator = DecisionTreeRegressor(), param_grid = {"criterion": ["mse", "friedman_mse", "mae", "poisson"],
                                                                       "splitter": ["best", "random"],
                                                                       "max_depth": [None,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
                                                                        }, cv=5)
grid_dt.fit(X_train_scaled, y_train)

/Users/timeisenmenger/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/Users/timeisenmenger/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/timeisenmenger/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 1242, in fit
    super().fit(
  File "/Users/timeisenmenger/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 336, in fit
    criterion = CRITERIA_REG[self.criterion](self.n_outputs_,
KeyError: 'poisson'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/timeisenmenger/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:548: FitFailedWarning: Estimato

GridSearchCV(cv=5, estimator=DecisionTreeRegressor(),
             param_grid={'criterion': ['mse', 'friedman_mse', 'mae', 'poisson'],
                         'max_depth': [None, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                       13, 14, 15, 16, 17, 18, 19, 20],
                         'splitter': ['best', 'random']})

In [35]:
grid_dt.best_params_

{'criterion': 'mse', 'max_depth': 7, 'splitter': 'random'}

In [36]:
y_pred_test_dt = grid_dt.predict(X_test_scaled)

In [37]:
y_pred_test_dt

array([7.60371517, 7.60371517, 7.60371517, 8.10643564, 7.576     ,
       7.576     , 8.06856024, 7.60371517, 8.06856024, 8.10643564,
       7.60371517, 8.06856024, 7.60371517, 8.06856024, 8.05714286,
       7.576     , 8.35714286, 7.12121212, 8.40298507, 8.06856024,
       8.10643564, 8.10643564, 8.06856024, 7.45017182, 7.29268293,
       6.95833333, 6.84210526, 7.60371517, 6.95833333, 7.45017182,
       8.06856024, 8.06856024, 7.12121212, 8.06856024, 8.06856024,
       8.10643564, 8.06856024, 8.06856024, 6.84210526, 8.10643564,
       8.10643564, 7.20454545, 7.89189189, 8.06856024, 7.576     ,
       7.60371517, 7.45017182, 8.10643564, 7.60371517, 8.10643564,
       7.576     , 7.60371517, 7.65217391, 8.10643564, 7.576     ,
       8.06856024, 7.576     , 6.84210526, 8.40298507, 8.98425197,
       7.576     , 8.06856024, 6.        , 8.06856024, 8.06856024,
       7.65217391, 7.45017182, 7.45017182, 7.45017182, 8.62441315,
       8.10643564, 8.62441315, 7.71052632, 7.12121212, 7.89189

## SVM Regression

In [7]:
from sklearn.svm import SVR

In [8]:
grid_SVR = GridSearchCV(estimator = SVR(), param_grid = {"kernel": ["linear", "poly", "rbf", "sigmoid"], "gamma": ["scale", "auto"], "epsilon": [0.1,0.2,0.3,0.4,0.5]}, cv=10)
grid_SVR.fit(X_train_scaled, y_train)

GridSearchCV(cv=10, estimator=SVR(),
             param_grid={'epsilon': [0.1, 0.2, 0.3, 0.4, 0.5],
                         'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [9]:
grid_SVR.best_params_

{'epsilon': 0.2, 'gamma': 'scale', 'kernel': 'rbf'}

In [11]:
y_pred_test_SVR = grid_SVR.predict(X_test_scaled)

In [12]:
y_pred_test_SVR 

array([7.37125381, 7.69841598, 7.78004358, 8.01114867, 7.88460159,
       7.17983175, 8.00806638, 6.7343378 , 8.08828568, 7.73957475,
       7.78014718, 7.69399398, 7.85600454, 8.08306929, 7.89675154,
       7.72736827, 7.94194583, 7.21648484, 8.01832511, 8.28361746,
       8.02613273, 8.08996374, 8.19582961, 7.76031297, 7.47028947,
       7.17686562, 7.06339388, 7.73747726, 7.13416539, 7.59672553,
       7.95311874, 7.83131905, 7.27861908, 7.72677295, 7.93634438,
       8.67130079, 8.08486744, 8.1001652 , 6.49354042, 7.72788605,
       8.17768387, 7.38310134, 7.83604011, 6.89378573, 6.97964483,
       7.21455583, 7.05003248, 8.20608056, 7.9247687 , 7.87092255,
       6.9414159 , 7.71844433, 7.17210297, 7.97543088, 7.01407888,
       8.20938378, 7.38229539, 7.1631978 , 7.7323251 , 8.56381663,
       7.27609505, 7.87154612, 6.82298557, 7.92669171, 8.02251797,
       7.5620595 , 7.59152892, 7.36823783, 7.21924897, 8.11214517,
       7.95140011, 8.43244839, 7.17972626, 6.41127751, 7.85742

In [13]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [14]:
RMSE = mean_squared_error(y_test, y_pred_test_SVR, squared=False)
r2 = r2_score(y_test, y_pred_test_SVR )

In [15]:
RMSE

0.7231971640201031

In [16]:
r2

0.5621555689649522

## Random Forest

In [9]:
from sklearn.ensemble import RandomForestRegressor

In [44]:
random_forest = RandomForestRegressor()
random_forest.fit(X_train_scaled, y_train)

RandomForestRegressor()

In [45]:
y_pred_test_rf_new = random_forest.predict(X_test_scaled)

In [46]:
y_pred_test_rf_new

array([ 7.78,  7.7 ,  7.76,  8.27,  7.41,  7.48,  8.28,  7.62,  7.3 ,
        7.96,  7.7 ,  7.82,  7.45,  8.56,  8.08,  7.5 ,  8.59,  7.65,
        8.08,  8.37,  7.91,  8.54,  8.17,  7.59,  7.53,  6.91,  7.14,
        7.46,  7.12,  7.2 ,  8.07,  7.79,  7.46,  7.78,  7.92,  8.51,
        9.62,  8.11,  6.92,  7.6 ,  7.93,  7.02,  7.94,  7.23,  7.23,
        7.5 ,  7.24,  8.11,  7.24,  7.85,  6.95,  7.94,  7.62,  7.7 ,
        7.78,  7.62,  7.42,  7.68,  8.25,  8.77,  7.5 ,  7.84,  7.1 ,
        8.25,  7.87,  7.79,  7.31,  7.6 ,  7.23,  8.28,  8.06,  8.62,
        6.57,  7.02,  8.09,  7.16,  7.68,  7.94,  7.44,  7.97,  7.37,
        8.13,  7.53,  8.92,  7.63,  8.26,  8.26,  7.65,  8.15,  9.57,
        7.82,  7.35,  7.68,  7.67,  7.5 ,  8.  ,  7.99,  8.33,  7.85,
        7.06,  8.86,  7.71,  9.41,  8.04,  8.63,  7.95,  7.43,  7.26,
        7.79,  8.79,  7.97,  7.18,  6.89,  7.34,  7.71,  7.23,  7.86,
        7.86,  9.15,  7.39,  7.86,  7.33,  6.82,  7.99,  7.8 ,  7.57,
        7.08,  7.92,

In [50]:
np.savetxt('/Users/timeisenmenger/Desktop/Ironhack /Week8/ML-Competition/Code/RF_without_param_cookies.csv', y_pred_test_rf_new, delimiter=',')

In [47]:
RMSE_rf = mean_squared_error(y_test, y_pred_test_rf_new, squared=False)
r2_rf = r2_score(y_test, y_pred_test_rf_new)

In [48]:
RMSE_rf

0.664598289006948

In [49]:
r2_rf

0.6302358186965087